#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PDF 文档模板管理器
基于 reportlab 库实现，支持中文、封面页、表格、图片等功能
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.colors import black, HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    Table, TableStyle, Image
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
import os
from datetime import datetime
import urllib.request


class PDFTemplate:
    """PDF 文档模板管理器"""

    # 默认资源 URL
    DEFAULT_BACKGROUND_URL = "https://ai.gov110.cn/webtools/download/background.jpeg"
    DEFAULT_FONT_URL = "https://ai.gov110.cn/webtools/download/SourceHanSansCN-Light.ttf"

    # 语言配置
    LANG_CONFIG = {
        'zh': {
            'author_label': '作者：',
            'table_prefix': '表',
            'figure_prefix': '图',
            'page_format': '第 {n} 页',
            'generated_by': '由 PDF Report 生成',
        },
        'en': {
            'author_label': 'Author: ',
            'table_prefix': 'Table',
            'figure_prefix': 'Figure',
            'page_format': 'Page {n}',
            'generated_by': 'Generated by PDF Report',
        }
    }

    def __init__(self, language='zh'):
        """
        初始化 PDF 模板管理器

        Args:
            language: 语言设置，'zh' 为中文，'en' 为英文，默认中文
        """
        self.story = []  # 存储所有内容元素
        self.styles = getSampleStyleSheet()
        self._table_counter = 0
        self._image_counter = 0
        self.header_text = ""
        self.page_width, self.page_height = A4
        self.cover_background = None

        # 语言设置
        self.language = language if language in self.LANG_CONFIG else 'zh'
        self.lang = self.LANG_CONFIG[self.language]

        # 设置字体
        self._setup_fonts()
        self._setup_custom_styles()
        self.font_config = self._get_font_config()

        # 初始化时自动设置默认封面背景图
        self.set_cover_background()

    def _setup_fonts(self):
        """设置中文字体支持（优先嵌入 TTF 字体，确保跨平台渲染一致）"""
        try:
            # 优先使用 TTF 嵌入字体（字体会嵌入 PDF，任何阅读器都能正确渲染）
            font_file = "SourceHanSansCN-Light.ttf"

            if not os.path.exists(font_file):
                print("[*] Downloading Chinese font...")
                try:
                    urllib.request.urlretrieve(self.DEFAULT_FONT_URL, font_file)
                    print(f"[+] Font downloaded: {font_file}")
                except Exception as e:
                    print(f"[-] Font download failed: {e}, trying built-in CID font...")
                    font_file = None

            if font_file and os.path.exists(font_file):
                try:
                    pdfmetrics.registerFont(TTFont('SourceHanSansCN', font_file))
                    self.chinese_font = 'SourceHanSansCN'
                    print(f"[+] Using embedded TTF font: {font_file}")
                    return
                except Exception as e:
                    print(f"[-] TTF font registration failed: {e}, trying built-in CID font...")

            # 降级：使用 reportlab 内置 CID 字体（不嵌入 PDF，依赖阅读器提供字体）
            try:
                pdfmetrics.registerFont(UnicodeCIDFont('STSong-Light'))
                self.chinese_font = 'STSong-Light'
                print("[*] Using built-in CID font: STSong-Light (not embedded, may not render in some viewers)")
                return
            except Exception:
                pass

            # 最终降级：ASCII 字体（不支持中文）
            self.chinese_font = 'Helvetica'
            print("[-] No Chinese font available, falling back to Helvetica")

        except Exception as e:
            print(f"[!] Font setup warning: {e}")
            self.chinese_font = 'Helvetica'

    def _get_font_config(self):
        """字体配置"""
        return {
            'title_font': self.chinese_font,
            'content_font': self.chinese_font,
            'sizes': {
                'title_1': 22, 'title_2': 18, 'title_3': 16, 'title_4': 14,
                'content': 12, 'small': 10.5, 'caption': 9, 'cover_title': 28,
                'cover_subtitle': 16, 'toc_title': 18, 'toc_item': 12
            }
        }

    def _setup_custom_styles(self):
        """设置自定义样式"""
        # 封面标题样式
        self.styles.add(ParagraphStyle(
            name='CoverTitle',
            parent=self.styles['Heading1'],
            fontSize=32,
            fontName=self.chinese_font,
            alignment=TA_CENTER,
            spaceAfter=20,
            spaceBefore=0,
            leading=38,
            textColor=HexColor('#000000')
        ))

        # 封面副标题样式
        self.styles.add(ParagraphStyle(
            name='CoverSubtitle',
            parent=self.styles['Normal'],
            fontSize=16,
            fontName=self.chinese_font,
            alignment=TA_CENTER,
            spaceAfter=30
        ))

        # 一级标题样式
        self.styles.add(ParagraphStyle(
            name='Title1',
            parent=self.styles['Heading1'],
            fontSize=22,
            fontName=self.chinese_font,
            alignment=TA_LEFT,
            spaceAfter=12,
            spaceBefore=18,
            leading=26
        ))

        # 二级标题样式
        self.styles.add(ParagraphStyle(
            name='Title2',
            parent=self.styles['Heading2'],
            fontSize=18,
            fontName=self.chinese_font,
            alignment=TA_LEFT,
            spaceAfter=9,
            spaceBefore=15,
            leading=22
        ))

        # 三级标题样式
        self.styles.add(ParagraphStyle(
            name='Title3',
            parent=self.styles['Heading3'],
            fontSize=16,
            fontName=self.chinese_font,
            alignment=TA_LEFT,
            spaceAfter=6,
            spaceBefore=12,
            leading=20
        ))

        # 四级标题样式
        self.styles.add(ParagraphStyle(
            name='Title4',
            parent=self.styles['Heading4'],
            fontSize=14,
            fontName=self.chinese_font,
            alignment=TA_LEFT,
            spaceAfter=6,
            spaceBefore=9,
            leading=18
        ))

        # 正文样式（带首行缩进）
        self.styles.add(ParagraphStyle(
            name='Content',
            parent=self.styles['Normal'],
            fontSize=12,
            fontName=self.chinese_font,
            alignment=TA_JUSTIFY,
            spaceAfter=6,
            firstLineIndent=24,  # 首行缩进 24 磅
            leading=18  # 1.5 倍行距
        ))

        # 表格说明样式
        self.styles.add(ParagraphStyle(
            name='TableCaption',
            parent=self.styles['Normal'],
            fontSize=10.5,
            fontName=self.chinese_font,
            alignment=TA_CENTER,
            spaceAfter=6,
            spaceBefore=3,
            textColor=HexColor('#404040')
        ))

        # 图片说明样式
        self.styles.add(ParagraphStyle(
            name='ImageCaption',
            parent=self.styles['Normal'],
            fontSize=10.5,
            fontName=self.chinese_font,
            alignment=TA_CENTER,
            spaceAfter=6,
            spaceBefore=3,
            textColor=HexColor('#404040')
        ))

    def _create_header_footer_template(self):
        """创建带页眉页脚的页面模板"""
        def header_footer(canvas, doc):
            canvas.saveState()
            canvas.setFont(self.chinese_font, 10.5)
            canvas.setFillColor(HexColor('#404040'))

            # 页眉文本（右对齐）
            if self.header_text:
                canvas.drawRightString(
                    self.page_width - 2*cm,
                    self.page_height - 1.5*cm,
                    self.header_text
                )

            # 页眉分隔线
            canvas.setStrokeColor(HexColor('#808080'))
            canvas.setLineWidth(0.5)
            canvas.line(
                2*cm,
                self.page_height - 2*cm,
                self.page_width - 2*cm,
                self.page_height - 2*cm
            )

            # 页脚页码 - 从正文页开始计算（跳过封面页）
            canvas.setFont(self.chinese_font, 10.5)
            page_num = canvas.getPageNumber() - 1  # 减去封面页
            if page_num > 0:
                page_text = self.lang['page_format'].format(n=page_num)
                canvas.drawCentredString(
                    self.page_width/2,
                    1*cm,
                    page_text
                )

            canvas.restoreState()

        return header_footer

    def add_cover_page(self, title, subtitle="", author="", date="",
                       organization="", additional_info=""):
        """添加封面页"""
        # 添加顶部空白，实现垂直居中效果
        self.story.append(Spacer(1, 140))

        # 封面标题
        cover_title = Paragraph(title, self.styles['CoverTitle'])
        self.story.append(cover_title)

        # 副标题
        if subtitle:
            cover_subtitle = Paragraph(subtitle, self.styles['CoverSubtitle'])
            self.story.append(cover_subtitle)

        # 标题区域后添加空行
        self.story.append(Spacer(1, 200))

        # 添加空行，将信息推到底部
        self.story.append(Spacer(1, 140))

        # 封面信息样式（白色字体）
        cover_info_style = ParagraphStyle(
            'CoverInfo',
            parent=self.styles['Normal'],
            fontSize=12,
            fontName=self.chinese_font,
            alignment=TA_CENTER,
            spaceAfter=12,
            textColor=HexColor('#FFFFFF')
        )

        # 作者信息
        if author:
            author_text = f"{self.lang['author_label']}{author}"
            author_para = Paragraph(author_text, cover_info_style)
            self.story.append(author_para)

        # 机构信息
        if organization:
            org_para = Paragraph(organization, cover_info_style)
            self.story.append(org_para)

        # 日期
        if date:
            date_para = Paragraph(date, cover_info_style)
            self.story.append(date_para)

        # 额外信息
        if additional_info:
            info_style = ParagraphStyle(
                'CoverAdditional',
                parent=self.styles['Normal'],
                fontSize=10.5,
                fontName=self.chinese_font,
                alignment=TA_CENTER,
                spaceAfter=12
            )
            info_para = Paragraph(additional_info, info_style)
            self.story.append(info_para)

        # 封面后分页
        self.story.append(PageBreak())

    def add_title(self, text, level=1, alignment=TA_LEFT):
        """添加标题"""
        style_name = f'Title{level}'
        if style_name in self.styles:
            title = Paragraph(text, self.styles[style_name])
        else:
            title = Paragraph(text, self.styles['Title1'])

        self.story.append(title)
        return title

    def add_content(self, text, first_line_indent=True):
        """添加正文内容"""
        if first_line_indent:
            content = Paragraph(text, self.styles['Content'])
        else:
            content = Paragraph(text, ParagraphStyle(
                'ContentNoIndent',
                parent=self.styles['Content'],
                firstLineIndent=0
            ))

        self.story.append(content)
        return content

    def add_table(self, rows, cols, data=None, style='medium', caption=None):
        """添加表格"""
        if data:
            # 计算最大宽度
            max_width = self.page_width - 5*cm

            # 根据列数设置列宽
            if cols == 8:
                col_widths = [
                    max_width * 0.12, max_width * 0.11, max_width * 0.11,
                    max_width * 0.12, max_width * 0.13, max_width * 0.13,
                    max_width * 0.14, max_width * 0.14
                ]
            else:
                col_widths = [max_width/cols] * cols

            # 将所有数据转换为 Paragraph 对象以实现自动换行
            processed_data = []
            for i, row in enumerate(data):
                processed_row = []
                for j, cell in enumerate(row):
                    cell_str = str(cell) if cell is not None else ""

                    if i == 0:  # 表头行
                        cell_para = Paragraph(cell_str, ParagraphStyle(
                            'TableHeader',
                            parent=self.styles['Normal'],
                            fontSize=11,
                            fontName=self.chinese_font,
                            alignment=TA_CENTER,
                            leading=13,
                            spaceBefore=2,
                            spaceAfter=2,
                            textColor=black
                        ))
                    else:  # 数据行
                        cell_para = Paragraph(cell_str, ParagraphStyle(
                            'TableCell',
                            parent=self.styles['Normal'],
                            fontSize=10,
                            fontName=self.chinese_font,
                            alignment=TA_CENTER,
                            leading=12,
                            spaceBefore=1,
                            spaceAfter=1,
                            textColor=black
                        ))
                    processed_row.append(cell_para)
                processed_data.append(processed_row)

            table = Table(processed_data, colWidths=col_widths)

            # 设置表格样式
            table_style = [
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('BACKGROUND', (0, 0), (-1, 0), HexColor('#F5F5F5')),
                ('GRID', (0, 0), (-1, -1), 1, black),
                ('LEFTPADDING', (0, 0), (-1, -1), 3),
                ('RIGHTPADDING', (0, 0), (-1, -1), 3),
                ('TOPPADDING', (0, 0), (-1, 0), 6),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
                ('TOPPADDING', (0, 1), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 4),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [None, HexColor('#FAFAFA')]),
            ]

            table.setStyle(TableStyle(table_style))
            self.story.append(table)

            # 添加表格说明
            if caption:
                self._table_counter += 1
                prefix = self.lang['table_prefix']
                caption_text = f"{prefix} <{self._table_counter}> {caption}"
                caption_para = Paragraph(caption_text, self.styles['TableCaption'])
                self.story.append(caption_para)

            self.story.append(Spacer(1, 6))
            return table
        else:
            empty_data = [[''] * cols for _ in range(rows)]
            table = Table(empty_data)
            table.setStyle(TableStyle([
                ('GRID', (0, 0), (-1, -1), 1, black),
            ]))
            self.story.append(table)
            return table

    def add_image(self, image_path, width=None, height=None, caption=None, auto_width=True):
        """添加图片"""
        try:
            if width and height:
                img = Image(image_path, width=width*cm, height=height*cm)
            elif width:
                calculated_height = width * 0.75
                img = Image(image_path, width=width*cm, height=calculated_height*cm)
            elif height:
                img = Image(image_path, height=height*cm)
            else:
                img = Image(image_path, width=14*cm, height=10.5*cm)

            img.hAlign = 'CENTER'
            self.story.append(img)

            if caption:
                self._image_counter += 1
                prefix = self.lang['figure_prefix']
                caption_text = f"{prefix} <{self._image_counter}> {caption}"
                caption_para = Paragraph(caption_text, self.styles['ImageCaption'])
                self.story.append(caption_para)

            self.story.append(Spacer(1, 6))
            return img

        except Exception as e:
            error_text = f"Image load failed: {image_path} (Error: {str(e)})"
            error_para = Paragraph(error_text, ParagraphStyle(
                'Error',
                parent=self.styles['Normal'],
                fontSize=10,
                fontName=self.chinese_font,
                textColor=HexColor('#FF0000')
            ))
            self.story.append(error_para)
            return None

    def add_page_break(self):
        """添加分页符"""
        self.story.append(PageBreak())

    def add_spacer(self, height=12):
        """添加间距"""
        self.story.append(Spacer(1, height))

    def set_cover_background(self, background_image_path=None):
        """设置封面背景图"""
        if background_image_path is None:
            background_image_path = "background.jpeg"
            if not os.path.exists(background_image_path):
                print("[*] Downloading default background...")
                try:
                    urllib.request.urlretrieve(
                        self.DEFAULT_BACKGROUND_URL,
                        background_image_path
                    )
                    print(f"[+] Background downloaded: {background_image_path}")
                except Exception as e:
                    print(f"[-] Background download failed: {e}")
                    background_image_path = None

        self.cover_background = background_image_path

    def save_document(self, filename):
        """保存 PDF 文档"""
        print("[*] Saving PDF document...")

        doc = SimpleDocTemplate(
            filename,
            pagesize=A4,
            rightMargin=2.5*cm,
            leftMargin=2.5*cm,
            topMargin=2.5*cm,
            bottomMargin=2.5*cm
        )

        def cover_with_background(canvas, doc):
            if self.cover_background and os.path.exists(self.cover_background):
                canvas.saveState()
                canvas.drawImage(
                    self.cover_background, 0, 0,
                    width=self.page_width, height=self.page_height
                )
                canvas.restoreState()

        header_footer = self._create_header_footer_template()

        if self.cover_background and os.path.exists(self.cover_background):
            doc.build(
                self.story,
                onFirstPage=cover_with_background,
                onLaterPages=header_footer
            )
        else:
            doc.build(
                self.story,
                onFirstPage=header_footer,
                onLaterPages=header_footer
            )

        # 添加最后一页封面
        self._add_last_page_cover(filename)

        print(f"[+] PDF saved: {filename}")
        return os.path.abspath(filename)

    def _add_last_page_cover(self, filename):
        """添加最后一页封面"""
        try:
            from PyPDF2 import PdfReader, PdfWriter
            import io
            from reportlab.pdfgen import canvas as pdf_canvas

            packet = io.BytesIO()
            can = pdf_canvas.Canvas(packet, pagesize=A4)

            if self.cover_background and os.path.exists(self.cover_background):
                can.drawImage(
                    self.cover_background, 0, 0,
                    width=self.page_width, height=self.page_height
                )

            can.setFont(self.chinese_font, 24)
            can.setFillColor(black)

            title_text = self.lang['generated_by']
            title_width = can.stringWidth(title_text, self.chinese_font, 24)
            title_x = (self.page_width - title_width) / 2
            title_y = self.page_height / 2 + 50
            can.drawString(title_x, title_y, title_text)

            can.save()

            packet.seek(0)
            new_pdf = PdfReader(packet)

            with open(filename, "rb") as f:
                existing_pdf = PdfReader(f)
                output = PdfWriter()

                for page in existing_pdf.pages:
                    output.add_page(page)

                output.add_page(new_pdf.pages[0])

                with open(filename, "wb") as output_stream:
                    output.write(output_stream)

            print("[+] Last page cover added")

        except ImportError:
            print("[!] PyPDF2 not installed, skipping last page cover")
        except Exception as e:
            print(f"[!] Failed to add last page cover: {e}")

    def get_document_info(self):
        """获取文档信息"""
        return {
            'total_elements': len(self.story),
            'table_count': self._table_counter,
            'image_count': self._image_counter,
            'page_size': f"{self.page_width/cm:.1f}cm x {self.page_height/cm:.1f}cm"
        }

    def show_template_help(self):
        """显示模板使用帮助"""
        help_text = """
PDF Template Usage Guide

1. Initialize
   from pdf_template import PDFTemplate
   manager = PDFTemplate()

2. Set header text
   manager.header_text = "Document Title"

3. Add cover page
   manager.add_cover_page(
       title="Report Title",
       subtitle="Subtitle",
       author="Author Name",
       date="2024-01-01"
   )

4. Add content
   manager.add_title("Chapter 1", level=1)
   manager.add_content("Paragraph text here.")

5. Add table
   data = [["Col1", "Col2"], ["Data1", "Data2"]]
   manager.add_table(2, 2, data, caption="Table description")

6. Add image
   manager.add_image("path/to/image.png", caption="Image description")

7. Save document
   manager.save_document("output.pdf")
        """
        print(help_text)


if __name__ == "__main__":
    # 简单测试 - 中文报告
    manager = PDFTemplate(language='zh')  # 默认中文
    manager.header_text = "测试报告"
    manager.add_cover_page(
        title="测试 PDF 报告",
        subtitle="由 PDF Report 技能生成",
        author="测试作者",
        date=datetime.now().strftime("%Y年%m月%d日")
    )
    manager.add_title("第一章 测试章节", level=1)
    manager.add_content("这是一个测试段落。")
    manager.save_document("test_output.pdf")
